image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: WebApplication3.sln

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\WebApplication3.UnitTests\bin\Debug\WebApplication3.UnitTests.dll -noshadow" -filter:"+[WebApplication3*]* -[WebApplication3.UnitTests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml"